### ISSUE TITLE
Create contributing.md file

### ISSUE THREAD

**Issue by Yadavanurag13** [schedulo-org/schedulo.com#3]
The project is in very early phase, we need a contributing.md file with details information about setting up and running project locally.
Backend is in django and frontend is in react.js.

**Comment by Apalakimmortal** [comment]
I would like to work on this issue

**Comment by Yadavanurag13** [comment]
Hey @Apalakimmortal  thank you for showing interest. you can refer to this [](https://github.com/djangoindia/djangoindia.org/issues/24)
